#docker-compose.yml
version: '3'
services:
  db:
    image: mongo:3.4.7
  api:
    build:
      context: .
      dockerfile: api_dockerfile
    depends_on:
      - db
  tests:
    build:
      context: .
      dockerfile: tests_dockerfile
    depends_on:
      - api
